name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build artifact
        run: echo ${{ github.sha }} > release_artifact.txt
      - name: Test artifact
        run: cat release_artifact.txt
      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: release_artifact.txt
      # https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test-pr
          title: 'this is a pull request that was auto-created by GitHub actions'
          commit-message: 'Test PR'
          delete-branch: true
          draft: false
